[[main]]
  name = "News"
  url = ""
  weight = 10

[[main]]
  name = "Property"
  url = "/property/"
  weight = 20

[[main]]
  name = "Business"
  url = "/business/"
  weight = 25

[[main]]
  name = "Rural"
  url = "/rural/"
  weight = 29

[[main]]
  name = "About Us"
  url = "/about/"
  weight = 30

[[main]]
  name = "Links"
  url = "/links/"
  identifier = "Links"
  weight = 45

[[main]]
  name = "Business Connect"
  url = "https://nzbusinessconnect.co.nz/"
  parent = "Links"
  weight = 10

[[main]]
  name = "MediaPA"
  url = "https://mediapa.co.nz/"
  parent = "Links"
  weight = 20

[[main]]
  name = "Boost Property"
  url = "https://www.facebook.com/BoostPropertyMedia"
  parent = "Links"
  weight = 30

[[main]]
  name = "Boost Business"
  url = "https://www.facebook.com/BoostProfessionalServices"
  parent = "Links"
  weight = 40

[[main]]
  name = "Boost Travel"
  url = "https://www.facebook.com/BoostTravel"
  parent = "Links"
  weight = 50

[[main]]
  name = "Boost Sustainability"
  url = "https://www.facebook.com/BoostSustainability"
  parent = "Links"
  weight = 60

[[main]]
  name = "<img src=\"/icons/mail.svg\" style=\"height:1.2rem; display: inline; margin: 0;\">"
  url = "/contact/"
  weight = 50